# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- None

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Pipeline'
  buildVersion: 'Will be set dynamically'
  revision: $[counter(format('{0:dd}', pipeline.startTime), 1)]

steps:
- task: PowerShell@2
  displayName: 'Install Modules'
  inputs:
    targetType: 'inline'
    script: |
      "Install Pester"|Write-Host
      Install-Module -Name Pester -Scope CurrentUser -Force;
      "Install psake"|Write-Host
      Install-Module -Name psake -Scope CurrentUser -Force;
      "Install PSDeploy"|Write-Host
      Install-Module -Name PSDeploy -Scope CurrentUser -Force;
      "Install PSScriptAnalyzer"|Write-Host
      Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force;
    pwsh: true

- task: PowerShell@2
  displayName: 'Preparing Build Number'
  inputs:
    targetType: 'inline'
    script: |
      $currentDate = $(Get-Date)
      $year = $currentDate.Year
      $month = $currentDate.Month
      $day = $currentDate.Day
      Write-Host $currentDate
      Write-Host $day
      Write-Host $env:revision
      Write-Host "##vso[task.setvariable variable=buildVersion]$year.$month.$day.$env:revision"
    pwsh: true

- task: PowerShell@2
  displayName: 'Analyze'
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
    arguments: ' -Task Analyze'
    pwsh: true

- task: PowerShell@2
  displayName: 'Test'
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
    arguments: ' -Task Test'
    pwsh: true

- task: PowerShell@2
  displayName: 'Build'
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
    arguments: ' -Task Build -BuildVersion $(buildVersion)'
    pwsh: true

- task: PowerShell@2
  displayName: 'ImportModule'
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
    arguments: ' -Task ImportModule'
    pwsh: true

- task: NuGetCommand@2
  displayName: 'Pack project'
  inputs:
    command: pack
    packagesToPack: '$(System.DefaultWorkingDirectory)/OmadaWeb.PS/OmadaWeb.PS.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar
    versionEnvVar: buildVersion
    buildProperties: 'VERSION=$(buildVersion)'
  condition: succeededOrFailed()

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: internal
    publishVstsFeed: 'Fortigi/OmadaWeb.PS'
    allowPackageConflicts: true
    packagesToPush: '$(Build.ArtifactStagingDirectory)/OmadaWeb.PS.$(buildVersion).nupkg'
