trigger:
- None

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Pipeline'
  buildVersion: 'Will be set dynamically'
  year: 'Will be set dynamically'
  revision: $[counter(format('{0:dd}', pipeline.startTime), 1)]


stages:
- stage: BuildStage
  jobs:
  - job: BuildJob
    steps:
    - task: PowerShell@2
      displayName: 'Install Modules'
      name: "InstallModules"
      inputs:
        targetType: 'inline'
        script: |
          "Validate Modules" | Write-Host
          $Modules = Get-Module -ListAvailable
          if ("Pester" -notin $Modules.Name) { 
            "Install Pester" | Write-Host
            Install-Module -Name Pester -Scope CurrentUser -Force 
          }
          if ("psake" -notin $Modules.Name) { 
            "Install psake" | Write-Host
            Install-Module -Name psake -Scope CurrentUser -Force 
          }
          if ("PSDeploy" -notin $Modules.Name) { 
            "Install PSDeploy" | Write-Host
            Install-Module -Name PSDeploy -Scope CurrentUser -Force 
          }
          if ("PSScriptAnalyzer" -notin $Modules.Name) { 
            "Install PSScriptAnalyzer" | Write-Host
            Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force 
          }
        pwsh: true
      condition: succeeded()

    - task: PowerShell@2
      displayName: 'Preparing Build Number'
      name: BuildVersioning
      inputs:
        targetType: 'inline'
        script: |
          $currentDate = $(Get-Date)
          $year = $currentDate.Year
          $month = $currentDate.Month
          $day = $currentDate.Day
          "Current date: {0}" -f $currentDate | Write-Host 
          "Current year: {0}" -f $year | Write-Host 
          "Current month: {0}" -f $month | Write-Host 
          "Current day: {0}" -f $day | Write-Host 
          "Revision: {0}" -f $env:revision | Write-Host 
          $versionString = "{0:d4}.{1:d2}.{2:d2}.{3}" -f $year,$month,$day,($env:revision -eq $null ? 0 : $env:revision)
          "Version: {0}" -f $versionString | Write-Host
          Write-Host "##vso[task.setvariable variable=buildVersion;isOutput=true]$versionString"
          Write-Host "##vso[task.setvariable variable=year;isOutput=true]$year"
        pwsh: true
      condition: succeeded()

    - task: PowerShell@2
      displayName: 'Build Module'
      name: "BuildTask"
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
        arguments: ' -Task Build -BuildVersion $(BuildVersioning.buildVersion)'
        pwsh: true
      condition: succeeded()

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Output'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/output'
        artifactName: 'BuildOutput'
      condition: succeeded()

- stage: PackageStage
  dependsOn: [BuildStage]
  jobs:
  - job: 'Create_Artifacts'
    variables:
      buildVersion: $[ stageDependencies.BuildStage.BuildJob.outputs['BuildVersioning.buildVersion'] ]
      year: $[ stageDependencies.BuildStage.BuildJob.outputs['BuildVersioning.year'] ]
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Output'
      inputs:
        artifactName: 'BuildOutput'
        targetPath: '$(System.DefaultWorkingDirectory)/output' 

    - task: NuGetCommand@2
      displayName: 'Pack project'
      inputs:
        command: pack
        packagesToPack: '$(System.DefaultWorkingDirectory)/OmadaWeb.PS.nuspec'
        packDestination: '$(Build.ArtifactStagingDirectory)'
        versioningScheme: byEnvVar
        versionEnvVar: buildVersion
        buildProperties: 'VERSION=$(BuildVersioning.buildVersion);YEAR=$(BuildVersioning.year)'
      condition: succeededOrFailed()

    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        nuGetFeedType: internal
        publishVstsFeed: 'Fortigi-Generic/OmadaWeb.PS'
        allowPackageConflicts: true
        packagesToPush: '$(Build.ArtifactStagingDirectory)/OmadaWeb.PS.$(BuildVersioning.buildVersion).nupkg'
      condition: succeeded()

    - script: |
        echo "Create tag: $(BuildVersioning.BuildVersion)"
        git config --global user.email "mark@fortigi.nl" 
        git config --global user.name "Mark van Eijken"
        git tag -a v$(BuildVersioning.BuildVersion) -m "Release version $(BuildVersioning.BuildVersion)"
        git push https://user:$(System.AccessToken)@dev.azure.com/fortigi/$(Build.Repository.Name) refs/tags/v$(BuildVersioning.BuildVersion)
      displayName: 'Create Tag'
      condition: succeeded()
      enabled: false
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- stage: GitHubStage
  dependsOn: [BuildStage, PackageStage]
  jobs:
  - deployment: GitHubJob
    environment: "GitHub"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Install GitHub CLI'
            inputs:
              targetType: 'inline'
              script: |
                "Installing GitHub CLI" | Write-Host
                Invoke-WebRequest -Uri https://github.com/cli/cli/releases/download/v2.63.2/gh_2.63.2_windows_amd64.msi -OutFile gh.msi
                Start-Process msiexec.exe -Wait -ArgumentList '/i gh.msi /quiet /norestart'
                "GitHub CLI installed successfully" | Write-Host

          - task: PowerShell@2
            displayName: 'Authenticate GitHub CLI'
            inputs:
              targetType: 'inline'
              script: |
                echo $(GITHUB_TOKEN) | gh auth login --with-token
            env:
              GITHUB_TOKEN: $(githubPAT)

          - task: PowerShell@2
            displayName: 'Push Files to GitHub Repository'
            inputs:
              targetType: 'inline'
              script: |
                git config --global user.email "mark@fortigi.nl"
                git config --global user.name "Mark van Eijken"
                git init
                git remote add origin https://$(githubPAT)@github.com/fortigi/OmadaWeb.PS.git
                git checkout -b main
                Copy-Item -Path "$(System.DefaultWorkingDirectory)/*" -Destination "./" -Recurse -Force
                git add .
                git commit -m "Release version $(BuildVersioning.buildVersion)"
                git push -u origin main

          - task: PowerShell@2
            displayName: 'Create GitHub Release'
            inputs:
              targetType: 'inline'
              script: |
                gh release create v$(BuildVersioning.buildVersion) "./*" --title "Release v$(BuildVersioning.buildVersion)" --notes "This is the release for version $(BuildVersioning.buildVersion)"
            env:
              GITHUB_TOKEN: $(githubPAT)

- stage: PSGalleryPublishStage
  dependsOn: [BuildStage, PackageStage]
  jobs:
  - deployment: PSGalleryPublishJob
    environment: "PSGallery"
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Output'
            inputs:
              artifactName: 'BuildOutput'
              targetPath: '$(System.DefaultWorkingDirectory)/output'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                "Publish module to PSGallery" | Write-Host 
                Get-childitem "$(System.DefaultWorkingDirectory)/output/OmadaWeb.PS" |Where-Object {$_.extension -notin (".psm1",".psd1")}| Remove-Item -Force
                Publish-Module -Path "$(System.DefaultWorkingDirectory)/output/OmadaWeb.PS" -NugetAPIKey "$(psgallery)" -Verbose