pool:
  name: PH

jobs:
- job: TestBuildJob
  steps:
  - task: PowerShell@2
    displayName: 'Install Modules'
    name: "InstallModules"
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/Build/InstallModules.ps1'
      pwsh: true
      failOnStderr: true
    condition: succeeded()

  - task: PowerShell@2
    displayName: 'Test Build Module'
    name: "BuildTask"
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/Build/build.ps1'
      arguments: ' -Task default -BuildVersion "1000.0" -Verbose'
      pwsh: true
      failOnStderr: true
    condition: succeeded()
