function Get-WebView2WindowTitle {
    [CmdletBinding()]
    PARAM(
        [parameter(Mandatory = $true)]
        [System.Uri]$Uri
    )

    # The full navigation URI carries login_hint, state and nonce query parameters generated by
    # New-EntraSignInUri. Showing it in the window title would put that information on screen and
    # in any screenshot, so only the host is shown.
    return "OmadaWeb.PS - {0}" -f $Uri.Host
}
